// PushService — background push notifications for job completions (research
// jobs, later other async work) via Firebase Cloud Messaging. Android-only:
// the desktop and web builds just skip initialization silently.
//
// FCM was chosen over a self-hosted UnifiedPush setup because it needs no
// extra app installed as a "distributor" — it's the same native channel every
// other Android app's notifications ride on. Trade-off: pushes transit
// Google's infrastructure rather than something self-hosted. Config comes
// from firebase_options.dart + android/app/google-services.json, both
// generated by `flutterfire configure` (project: com-qstivi-eva).
//
// eva-task-runner sends data-only messages (see fcm.py) rather than a
// "notification" payload deliberately: with a "notification" payload,
// Android auto-displays it itself whenever the app isn't foregrounded *and*
// our own onMessage handler can also fire and show it again, producing
// duplicates (seen in testing — including once with an empty body, when the
// duplicate fired without the notification block attached). Data-only means
// _showJobNotification below is the only thing that ever displays one, in
// every app state — foreground (via onMessage) and background/killed (via
// the top-level background handler, which runs in its own isolate and so
// re-initializes Firebase and local-notifications from scratch).
import 'dart:convert';
import 'dart:io';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:http/http.dart' as http;
import 'package:url_launcher/url_launcher.dart';

import '../config/eva_settings.dart';
import '../firebase_options.dart';

/// Fixed base for reaching the runner — it's loopback-only on the host, only
/// reachable at all via the same public tunnel + Access gate as chat.
const String _kRunnerBase = 'https://eva.qstivi.com';

/// Runs in a separate background isolate spawned by the OS/FCM when a
/// message arrives and the app isn't foregrounded — none of PushService's
/// instance state (its already-initialized plugin, Firebase app, etc.)
/// carries over, so this re-initializes everything it needs from scratch.
/// Must stay a top-level function for the isolate entry point to find it.
@pragma('vm:entry-point')
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  final notifications = FlutterLocalNotificationsPlugin();
  await notifications.initialize(
    const InitializationSettings(
      android: AndroidInitializationSettings('@mipmap/ic_launcher'),
    ),
    // Runs when a background/killed-state notification is tapped. Must stay
    // a top-level/static-reachable callback — this whole handler runs in its
    // own isolate, same reason firebaseMessagingBackgroundHandler itself must.
    onDidReceiveNotificationResponse: _onNotificationTapped,
  );
  await _showJobNotification(notifications, message.data);
}

/// Tap handler for a shown notification, wired in both the foreground
/// (_initLocalNotifications) and background (the handler above) init calls.
/// The payload is the raw FCM data map, JSON-encoded — see
/// _showJobNotification. Only "approval" pushes carry a jobsUrl; anything
/// else (job-completion pushes, etc.) just brings the app forward, which the
/// OS already does on tap without any code here.
@pragma('vm:entry-point')
void _onNotificationTapped(NotificationResponse response) {
  final payload = response.payload;
  if (payload == null || payload.isEmpty) return;
  try {
    final data = jsonDecode(payload) as Map<String, dynamic>;
    if (data['type'] == 'approval') {
      final url = data['jobsUrl'] as String?;
      if (url != null) {
        launchUrl(Uri.parse(url), mode: LaunchMode.externalApplication);
      }
    }
  } catch (e) {
    debugPrint('PushService: bad notification payload: $e');
  }
}

/// Builds the one-tap eva-web /jobs URL, Basic-auth credentials embedded so
/// tapping the notification doesn't stop at a login prompt — matches the
/// plan's "should still be one tap" goal for the v1 approval surface (see
/// docs/2026-08-22-delegate-to-claude-spec.md). Empty if either credential
/// is unset (auth disabled, or not configured yet) since embedding an empty
/// `:@` userinfo segment reads as malformed to some URL parsers.
String? _jobsUrl(EvaSettings settings) {
  final uri = Uri.tryParse(settings.webBaseUrl);
  if (uri == null) return null;
  if (settings.chatUser.isEmpty || settings.chatPassword.isEmpty) {
    return uri.replace(path: '/jobs').toString();
  }
  return uri
      .replace(
        userInfo: '${Uri.encodeComponent(settings.chatUser)}:${Uri.encodeComponent(settings.chatPassword)}',
        path: '/jobs',
      )
      .toString();
}

Future<void> _showJobNotification(
    FlutterLocalNotificationsPlugin notifications, Map<String, dynamic> data) async {
  // Payload carries the type + a ready-to-launch jobsUrl (looked up fresh
  // here, not baked in at push time, so it always reflects the device's
  // current settings) — built once, used by _onNotificationTapped above.
  String? payload;
  if (data['type'] == 'approval') {
    try {
      final settings = await EvaSettings.load();
      final url = _jobsUrl(settings);
      if (url != null) {
        payload = jsonEncode({'type': 'approval', 'jobsUrl': url});
      }
    } catch (e) {
      debugPrint('PushService: could not build approval jobsUrl: $e');
    }
  }
  await notifications.show(
    DateTime.now().millisecondsSinceEpoch ~/ 1000,
    (data['title'] as String?) ?? 'Eva',
    (data['body'] as String?) ?? '(no details)',
    const NotificationDetails(
      android: AndroidNotificationDetails(
        'eva_jobs',
        'Background jobs',
        channelDescription: 'Research and other background job results',
        importance: Importance.high,
        priority: Priority.high,
      ),
    ),
    payload: payload,
  );
}

class PushService {
  PushService._();
  static final PushService instance = PushService._();

  final FlutterLocalNotificationsPlugin _notifications =
      FlutterLocalNotificationsPlugin();
  EvaSettings? _settings;

  /// Called whenever a push arrives while the app is in the foreground —
  /// wired by main.dart to EvaController.refreshMessages() so the transcript
  /// actually picks up what just arrived (a check-in reply, a job result)
  /// instead of only showing it after a force-quit and reopen. Background/
  /// killed-state pushes don't need this: connect()'s own history load on
  /// the next real app start already gets it right.
  void Function()? onForegroundPush;

  /// Initializes Firebase, requests notification permission, registers the
  /// background handler, and registers the device's FCM token with
  /// eva-task-runner. Safe to call on any platform — it's a no-op off
  /// Android. Best-effort throughout: a missing google-services.json, a dead
  /// runner, or a denied permission just means no push this session, not a
  /// startup failure.
  Future<void> init(EvaSettings settings) async {
    _settings = settings;
    if (kIsWeb || !Platform.isAndroid) return;

    await _initLocalNotifications();

    try {
      await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
      FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);

      final messaging = FirebaseMessaging.instance;
      await messaging.requestPermission();

      final token = await messaging.getToken();
      if (token != null) _postToRunner('/push/register', token);
      messaging.onTokenRefresh.listen((t) => _postToRunner('/push/register', t));

      FirebaseMessaging.onMessage.listen((message) {
        _showJobNotification(_notifications, message.data);
        onForegroundPush?.call();
      });
    } catch (e) {
      debugPrint('PushService: init failed (no push this session): $e');
    }
  }

  Future<void> _initLocalNotifications() async {
    const androidInit = AndroidInitializationSettings('@mipmap/ic_launcher');
    await _notifications.initialize(
      const InitializationSettings(android: androidInit),
      onDidReceiveNotificationResponse: _onNotificationTapped,
    );
    await _notifications
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.requestNotificationsPermission();
  }

  Future<void> _postToRunner(String path, String fcmToken) async {
    final settings = _settings;
    if (settings == null) return;
    try {
      await http.post(
        Uri.parse('$_kRunnerBase$path'),
        headers: {
          'Content-Type': 'application/json',
          ...settings.accessHeaders,
        },
        body: jsonEncode({'token': fcmToken}),
      );
    } catch (e) {
      debugPrint('PushService: could not reach runner ($path): $e');
    }
  }
}
