// PushService — background push notifications for job completions (research
// jobs, later other async work) via Firebase Cloud Messaging. Android-only:
// the desktop and web builds just skip initialization silently.
//
// FCM was chosen over a self-hosted UnifiedPush setup because it needs no
// extra app installed as a "distributor" — it's the same native channel every
// other Android app's notifications ride on. Trade-off: pushes transit
// Google's infrastructure rather than something self-hosted. Config comes
// from firebase_options.dart + android/app/google-services.json, both
// generated by `flutterfire configure` (project: com-qstivi-eva).
//
// eva-task-runner sends data-only messages (see fcm.py) rather than a
// "notification" payload deliberately: with a "notification" payload,
// Android auto-displays it itself whenever the app isn't foregrounded *and*
// our own onMessage handler can also fire and show it again, producing
// duplicates (seen in testing — including once with an empty body, when the
// duplicate fired without the notification block attached). Data-only means
// _showJobNotification below is the only thing that ever displays one, in
// every app state — foreground (via onMessage) and background/killed (via
// the top-level background handler, which runs in its own isolate and so
// re-initializes Firebase and local-notifications from scratch).
import 'dart:convert';
import 'dart:io';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:http/http.dart' as http;

import '../config/eva_settings.dart';
import '../firebase_options.dart';
import '../screens/approvals_screen.dart';
import '../state/eva_controller.dart';

/// Fixed base for reaching the runner — it's loopback-only on the host, only
/// reachable at all via the same public tunnel + Access gate as chat.
const String _kRunnerBase = 'https://eva.qstivi.com';

/// Runs in a separate background isolate spawned by the OS/FCM when a
/// message arrives and the app isn't foregrounded — none of PushService's
/// instance state (its already-initialized plugin, Firebase app, etc.)
/// carries over, so this re-initializes everything it needs from scratch.
/// Must stay a top-level function for the isolate entry point to find it.
@pragma('vm:entry-point')
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  final notifications = FlutterLocalNotificationsPlugin();
  await notifications.initialize(
    const InitializationSettings(
      android: AndroidInitializationSettings('@mipmap/ic_launcher'),
    ),
    // Runs when a background/killed-state notification is tapped. Must stay
    // a top-level/static-reachable callback — this whole handler runs in its
    // own isolate, same reason firebaseMessagingBackgroundHandler itself must.
    onDidReceiveNotificationResponse: _onNotificationTapped,
  );
  await _showJobNotification(notifications, message.data);
}

/// Tap handler for a shown notification, wired in both the foreground
/// (_initLocalNotifications) and background (the handler above) init calls.
/// Only reachable while the app's main isolate is alive (foreground or
/// backgrounded-but-running) — a tap that relaunches a fully killed app
/// doesn't go through this at all; see PushService.checkLaunchedFromApproval
/// for that path. Payload is just the push's "type" string (see
/// _showJobNotification) — "approval" opens the Approvals screen in-app.
///
/// This used to launch eva-web's /jobs page in the system browser instead —
/// dropped after that produced a Cloudflare Access 403 in practice (a bare
/// browser tab carries none of the Access service-token headers the app
/// itself sends on every request). Going in-app sidesteps that outright: the
/// app already has those headers, so it just calls eva-web's API directly.
@pragma('vm:entry-point')
void _onNotificationTapped(NotificationResponse response) {
  if (response.payload == 'approval') PushService._openApprovals();
}

Future<void> _showJobNotification(
    FlutterLocalNotificationsPlugin notifications, Map<String, dynamic> data) async {
  final payload = data['type'] == 'approval' ? 'approval' : null;
  await notifications.show(
    DateTime.now().millisecondsSinceEpoch ~/ 1000,
    (data['title'] as String?) ?? 'Eva',
    (data['body'] as String?) ?? '(no details)',
    const NotificationDetails(
      android: AndroidNotificationDetails(
        'eva_jobs',
        'Background jobs',
        channelDescription: 'Research and other background job results',
        importance: Importance.high,
        priority: Priority.high,
      ),
    ),
    payload: payload,
  );
}

class PushService {
  PushService._();
  static final PushService instance = PushService._();

  final FlutterLocalNotificationsPlugin _notifications =
      FlutterLocalNotificationsPlugin();
  EvaSettings? _settings;

  /// Attached to MaterialApp in main.dart so a tapped notification can push a
  /// route without needing a BuildContext of its own — the tap handler above
  /// runs outside any widget's build.
  static final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

  /// The live EvaController, set once from main.dart right after it's
  /// created (before PushService.init, so it's ready before any tap could
  /// plausibly land). Static/nullable rather than passed through init()
  /// because _onNotificationTapped is a top-level function reached from
  /// contexts that don't carry instance state.
  static EvaController? _controller;
  static void bindController(EvaController controller) => _controller = controller;

  static void _openApprovals() {
    final nav = navigatorKey.currentState;
    final controller = _controller;
    if (nav == null || controller == null) return;
    nav.push(MaterialPageRoute(
      builder: (_) => Scaffold(
        appBar: AppBar(title: const Text('Approvals')),
        body: ApprovalsScreen(controller: controller),
      ),
    ));
  }

  /// Call once at startup (after runApp, once the navigator exists) to catch
  /// the case _onNotificationTapped can't: the app was fully killed and this
  /// launch IS the tap. flutter_local_notifications hands this back via its
  /// own launch-details API rather than routing through the normal tap
  /// callback for a cold start.
  Future<void> checkLaunchedFromApproval() async {
    if (kIsWeb || !Platform.isAndroid) return;
    try {
      final details = await _notifications.getNotificationAppLaunchDetails();
      if (details?.didNotificationLaunchApp == true &&
          details?.notificationResponse?.payload == 'approval') {
        PushService._openApprovals();
      }
    } catch (e) {
      debugPrint('PushService: could not check launch details: $e');
    }
  }

  /// Called whenever a push arrives while the app is in the foreground —
  /// wired by main.dart to EvaController.refreshMessages() so the transcript
  /// actually picks up what just arrived (a check-in reply, a job result)
  /// instead of only showing it after a force-quit and reopen. Background/
  /// killed-state pushes don't need this: connect()'s own history load on
  /// the next real app start already gets it right.
  void Function()? onForegroundPush;

  /// Initializes Firebase, requests notification permission, registers the
  /// background handler, and registers the device's FCM token with
  /// eva-task-runner. Safe to call on any platform — it's a no-op off
  /// Android. Best-effort throughout: a missing google-services.json, a dead
  /// runner, or a denied permission just means no push this session, not a
  /// startup failure.
  Future<void> init(EvaSettings settings) async {
    _settings = settings;
    if (kIsWeb || !Platform.isAndroid) return;

    await _initLocalNotifications();

    try {
      await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
      FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);

      final messaging = FirebaseMessaging.instance;
      await messaging.requestPermission();

      final token = await messaging.getToken();
      if (token != null) _postToRunner('/push/register', token);
      messaging.onTokenRefresh.listen((t) => _postToRunner('/push/register', t));

      FirebaseMessaging.onMessage.listen((message) {
        _showJobNotification(_notifications, message.data);
        onForegroundPush?.call();
      });
    } catch (e) {
      debugPrint('PushService: init failed (no push this session): $e');
    }
  }

  Future<void> _initLocalNotifications() async {
    const androidInit = AndroidInitializationSettings('@mipmap/ic_launcher');
    await _notifications.initialize(
      const InitializationSettings(android: androidInit),
      onDidReceiveNotificationResponse: _onNotificationTapped,
    );
    await _notifications
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.requestNotificationsPermission();
  }

  Future<void> _postToRunner(String path, String fcmToken) async {
    final settings = _settings;
    if (settings == null) return;
    try {
      await http.post(
        Uri.parse('$_kRunnerBase$path'),
        headers: {
          'Content-Type': 'application/json',
          ...settings.accessHeaders,
        },
        body: jsonEncode({'token': fcmToken}),
      );
    } catch (e) {
      debugPrint('PushService: could not reach runner ($path): $e');
    }
  }
}
