// PushService — background push notifications for job completions (research
// jobs, later other async work) via Firebase Cloud Messaging. Android-only:
// the desktop and web builds just skip initialization silently.
//
// FCM was chosen over a self-hosted UnifiedPush setup because it needs no
// extra app installed as a "distributor" — it's the same native channel every
// other Android app's notifications ride on. Trade-off: pushes transit
// Google's infrastructure rather than something self-hosted. Config comes
// from firebase_options.dart + android/app/google-services.json, both
// generated by `flutterfire configure` (project: com-qstivi-eva).
//
// When the app is backgrounded/killed, Android shows the notification itself
// (we send a "notification" payload, not data-only) — no code here runs for
// that case. When the app is in the foreground, FCM does NOT auto-display,
// so onMessage below shows it via flutter_local_notifications instead.
import 'dart:convert';
import 'dart:io';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:http/http.dart' as http;

import '../config/eva_settings.dart';
import '../firebase_options.dart';

/// Fixed base for reaching the runner — it's loopback-only on the host, only
/// reachable at all via the same public tunnel + Access gate as chat.
const String _kRunnerBase = 'https://eva.qstivi.com';

class PushService {
  PushService._();
  static final PushService instance = PushService._();

  final FlutterLocalNotificationsPlugin _notifications =
      FlutterLocalNotificationsPlugin();
  EvaSettings? _settings;
  bool _localNotifsReady = false;

  /// Initializes Firebase, requests notification permission, and registers
  /// the device's FCM token with eva-task-runner. Safe to call on any
  /// platform — it's a no-op off Android. Best-effort throughout: a missing
  /// google-services.json, a dead runner, or a denied permission just means
  /// no push this session, not a startup failure.
  Future<void> init(EvaSettings settings) async {
    _settings = settings;
    if (kIsWeb || !Platform.isAndroid) return;

    await _initLocalNotifications();

    try {
      await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
      final messaging = FirebaseMessaging.instance;
      await messaging.requestPermission();

      final token = await messaging.getToken();
      if (token != null) _postToRunner('/push/register', token);
      messaging.onTokenRefresh.listen((t) => _postToRunner('/push/register', t));

      FirebaseMessaging.onMessage.listen(_onForegroundMessage);
    } catch (e) {
      debugPrint('PushService: init failed (no push this session): $e');
    }
  }

  Future<void> _initLocalNotifications() async {
    const androidInit = AndroidInitializationSettings('@mipmap/ic_launcher');
    await _notifications.initialize(
      const InitializationSettings(android: androidInit),
    );
    await _notifications
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.requestNotificationsPermission();
    _localNotifsReady = true;
  }

  Future<void> _onForegroundMessage(RemoteMessage message) async {
    if (!_localNotifsReady) return;
    final title = message.notification?.title ?? 'Eva';
    final body = message.notification?.body ?? jsonEncode(message.data);
    await _notifications.show(
      DateTime.now().millisecondsSinceEpoch ~/ 1000,
      title,
      body,
      const NotificationDetails(
        android: AndroidNotificationDetails(
          'eva_jobs',
          'Background jobs',
          channelDescription: 'Research and other background job results',
          importance: Importance.high,
          priority: Priority.high,
        ),
      ),
    );
  }

  Future<void> _postToRunner(String path, String fcmToken) async {
    final settings = _settings;
    if (settings == null) return;
    try {
      await http.post(
        Uri.parse('$_kRunnerBase$path'),
        headers: {
          'Content-Type': 'application/json',
          ...settings.accessHeaders,
        },
        body: jsonEncode({'token': fcmToken}),
      );
    } catch (e) {
      debugPrint('PushService: could not reach runner ($path): $e');
    }
  }
}
